---
- hosts: "{{ variable_host | default('network') }}"
  sudo: yes
  tasks:
  - name: Show Cumulus Linux BGP summary
    command: sudo cl-bgp summary

  - name: Show Cumulus Linux BGP neighbor
    command: sudo cl-bgp neighbor show all

  - name: Show IP Routes
    command: ip route
