---
- hosts: "{{ variable_host | default('network') }}"
  sudo: yes
  tasks:
  - name: Show Hostname
    command: hostname
    register: hostname_output
    #- debug: var=hostname_output.stdout.split('\n')
  - debug: msg="{{ hostname_output.stdout }}"
    
  - name: Show Interfaces
    command: cat /etc/network/interfaces
    
  - name: Netshow Interfaces
    command: netshow interface

  - name: Show Router configurations
    command: cat /etc/quagga/Quagga.conf
