---
- hosts: "{{ variable_host | default('network') }}"
  sudo: yes
  tasks:
  - name: Show Hostname
    command: hostname
    register: hostname
  - debug: var=hostname.stdout.split('\n')
    
  - name: Show Interfaces
    command: cat /etc/network/interfaces
    
  - name: Netshow Interfaces
    command: netshow interface

  - name: Show Router configurations
    command: cat /etc/quagga/Quagga.conf
