---
- hosts: "{{ variable_host | default('network') }}"
  sudo: yes
  tasks:
  - name: Show Hostname
    command: {{ item }}
    with_items:
    - hostname
      register: hostname_output
    - debug: var=hostname_output.stdout.split('\n')
    
  - name: Show Interfaces
    command: cat /etc/network/interfaces
    
  - name: Netshow Interfaces
    command: netshow interface

  - name: Show Router configurations
    command: cat /etc/quagga/Quagga.conf
