---
- hosts: network
  sudo: yes
  tasks:
  - name: Copy Default Interfaces File to each Switch
    copy: src=/home/cumulus/vx-demo-files-master/defaults/interfaces.orig dest=/etc/network/interfaces

  - name: Copy Default Quagga Daemons File to each Switch
    copy: src=/home/cumulus/vx-demo-files-master/defaults/daemons.orig dest=/etc/quagga/daemons

  - name: Reprovision Quagga to defaults
    command: rm /etc/quagga/Quagga.conf

  - name: Reboot Switches
    command: reboot
